openapi: 3.0.1
info:
  title: Developer API
  description: Full documentation API for Social Media Project
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1
    description: Local development server
tags:
  - name: Authentication
  - name: Post

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /auth/signup: